### ISSUE TITLE
ERROR = 1 - message import export file / Chrome and Explorer 

### ISSUE THREAD

**Issue by ovba2020** [khrazy5150/ovba#1]
*POTENTIAL BUG REPORT*

1) On what device/operating system did the error occur? (e.g.: Mac Laptop with MacOS Mojave version 10.14.1; HP Laptop with Windows 10; iPhone with iOS 12)

DESKTOP LENOVO 
WINDOWS 10 

2) What browser where you using (e.g.: Chrome, Safari, Firefox, etc.)
BROWSER = CHROME pix attached 

3) Does the issue occur in another browser? If so which ones?
yes with EXPLORER  same problem pix attached

*REPORT DATA*
A Description of the Issue: 
Error message when we upload the XL document called Franklin 
Both members have valid created emails 

Page URL:
 http://ovba.net/Contract/Add#

Supporting Video or Screenshots:

 
![test-1-chrome](https://user-images.githubusercontent.com/45092131/48663015-deb3d700-ea3e-11e8-8fbf-dede16657940.JPG)
![test-1-explorer](https://user-images.githubusercontent.com/45092131/48663017-deb3d700-ea3e-11e8-8322-b5ad9b8a296b.JPG)

*STEPS TO REPRODUCE* (Describe in detail what you did to get this error. If it's the result of data entry, include the EXACT DATA that was entered)

1) just uploaded the XL in the contract / members / upload section

2)

3)

*EXPECTED RESULT* (Describe what did you expect the system to do [e.g.: send an email, redirect to another page, etc.])

I guess to have these 2 members data uploaded under this contract and have them covered by the agreement for RX coverage 

*ACTUAL RESULT* (Describe what actually happens. If you get an error, describe the error message.)

ERROR MESSAGE PICTURE ATTACHED with Explorer and Chrome Browsers

**Comment by khrazy5150** [comment]
FIXED
