### ISSUE TITLE
ERROR = 14 - REMOVING - ITEM FROM PRODUCT SCREEN MENU

### ISSUE THREAD

**Issue by ovba2020** [khrazy5150/ovba#14]
*POTENTIAL BUG REPORT*

1) On what device/operating system did the error occur? (e.g.: Mac Laptop with MacOS Mojave version 10.14.1; HP Laptop with Windows 10; iPhone with iOS 12)
SURFACE PRO-5
WINDOWS10

2) What browser where you using (e.g.: Chrome, Safari, Firefox, etc.)
CHROME AND FIREFOX

3) Does the issue occur in another browser? If so which ones?
CHROME AND FIREFOX 

*REPORT DATA*
A Description of the Issue:
TRIED ADDING EDGE-03 IN WRONG CATEGORY AND NOW TRYING TO DELETE IT
AND IT WILL NOT DELETE THE ITEM ADDED 

Page URL:
http://ovba.net/Product/SpecExam

Supporting Video or Screenshots:
![error-14-removing-edge-03-error](https://user-images.githubusercontent.com/45092131/48973524-f6b6c800-eff5-11e8-9344-7f7f683c9315.JPG)

![error-14-removing-edge-03](https://user-images.githubusercontent.com/45092131/48973526-f9b1b880-eff5-11e8-99d1-40d707bc1d75.JPG)

![inkederror-14-removing-edge-03_li](https://user-images.githubusercontent.com/45092131/48973566-ccb1d580-eff6-11e8-9233-2b7f916bce17.jpg)

*STEPS TO REPRODUCE* (Describe in detail what you did to get this error. If it's the result of data entry, include the EXACT DATA that was entered)
1) ADDED EDGE-03 IN THE PRODUCT MENU AS A LENS 

2) TRYING TO DELETE IT FROM THE LENS SECTION 

3)

*EXPECTED RESULT* (Describe what did you expect the system to do [e.g.: send an email, redirect to another page, etc.])
SYSTEM WOULD ALLOW ME TO DELETE THIS ITEM PLACED IN THE WRONG SECTION

*ACTUAL RESULT* (Describe what actually happens. If you get an error, describe the error message.)
GET AN ERROR MESSAGE 
AND THE ITEM IS STILL THERE

**Comment by khrazy5150** [comment]
FIXED
